AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  schemavalidatexmltojson

  SAM Template for schemavalidatexmltojson project.

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  RequestsTable:
    Type: AWS::DynamoDB::Table
    Properties: 
      AttributeDefinitions: 
        - AttributeName: id
          AttributeType: S
      KeySchema: 
        - AttributeName: id
          KeyType: HASH
      ProvisionedThroughput: 
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
  PayloadBucket:
    Type: AWS::S3::Bucket
  GetXmlFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: get_xml/
      Handler: app.lambda_handler
      Runtime: python3.9
      Architectures:
        - x86_64
      Environment:
        Variables:
          PAYLOAD_BUCKET: !Ref PayloadBucket
          DYNAMODB_TABLE: !Ref RequestsTable
          EVENTBRIDGE: !Ref EventBus
          REGION: "us-east-1"
      Events:
        GetXml:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /xml
            Method: post
  EventBus:
    Type: AWS::Events::EventBus
    Properties: 
      Name: "schemavalidator_bus"
Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  GetXmlApi:
    Description: "API Gateway endpoint URL for Prod stage for GetXml function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/xml/"
  GetXmlFunction:
    Description: "Get XML Lambda Function ARN"
    Value: !GetAtt GetXmlFunction.Arn
  GetXmlFunctionIamRole:
    Description: "Implicit IAM Role created for Get XML function"
    Value: !GetAtt GetXmlFunction.Arn
